### ISSUE TITLE
Logo is not reponsive

### ISSUE THREAD

**Issue by aasthasona79** [aasthasona79/lnmiit_tpc#6]
LNMIIT's logo is not responsive. When is screen size is reduced, its position is disturbed and it looks something like this-

![image](https://user-images.githubusercontent.com/11635732/29273833-5947c62e-8123-11e7-85e2-70e30486eb44.png)

![image](https://user-images.githubusercontent.com/11635732/29273843-65738456-8123-11e7-979c-21c22728875b.png)

**Comment by Vedarth** [comment]
I don't think it's an issue anymore.
